spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ironoc-net-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      topic: ironoc-test-topic
      enable-auto-commit: false
    listener:
      missing-topics-fatal: false

logging:
  level:
    root: INFO
    net.ironoc.kafka.listener: DEBUG
